
export const moviedata =[
    {  id:1,
        title:'RED NOTICE',
        type:'action',
        date:2021,
        description:`An Interpol agent successfully tracks down the world's most wanted art thief, 
        with help from a rival thief. But nothing is as it seems, as a series of double-crosses ensue.`,
        trailer:"https://www.youtube.com/embed/uKaWIwGc-j8",
        posterUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
        rating:5},
    {id:2,
        title:'INCEPTION',
        type:'action',
        date:2010,
        description:`A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting 
        an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.`,
        trailer:"https://www.youtube.com/embed/YoHD9XEInc0",
        posterUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg",
        rating:4},
    {id:3,
        title:'GLASS ONION',
        type:'Comedy',
        date:2022,
        description:`Famed Southern detective Benoit Blanc travels to Greece for his latest case.`,
        trailer:"https://www.youtube.com/embed/gj5ibYSz8C0",
        posterUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
        rating:4},
    {  id:4,
        title:'RED NOTICE',
        type:'action',
        date:2021,
        description:`An Interpol agent successfully tracks down the world's most wanted art thief, 
        with help from a rival thief. But nothing is as it seems, as a series of double-crosses ensue.`,
        trailer:"https://www.youtube.com/embed/uKaWIwGc-j8",
        posterUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
        rating:5},
    {  id:5,
            title:'RED NOTICE',
            type:'action',
            date:2021,
            description:`An Interpol agent successfully tracks down the world's most wanted art thief, 
            with help from a rival thief. But nothing is as it seems, as a series of double-crosses ensue.`,
            trailer:"https://www.youtube.com/embed/uKaWIwGc-j8",
            posterUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
            rating:5},
     
     
]
